version: '3'
services:
  db:
    container_name: cmt_mariadb
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    container_name: cmt_wordpress
    image: wordpress:latest
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    volumes: 
      - ./mongo/data:/data/db
  rabbitmq:
    image: "rabbitmq:3.12.12-management-alpine"  
    container_name: 'rabbitmq'
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      - mongo
volumes:
  mongo:
  rabbitmq:
  db_data:
  wp_data:


